<?php
	## System Setup ##
	Reg::set("System.mode", "development");
	
	## URI Setup ##
	Reg::set(array(
		"URI.useModRewrite" => true,
		"URI.useDashes" => true,
		"URI.forceDashes" => true
	));
	
	Reg::set(array("URI.map" => array(
		//"lang"			=> array("en", create_function('$element', 'return preg_match("/(en|sp)/i", $element);')),
		"lang"			=> array("en", array('Validation_Helper', 'checkLanguage')),
		"controller"	=> "main",
		"view"			=> "index",
		"action"		=> null,
		"id"			=> null
	)));
	
	//Reg::set("URI.prependIdentifier", "another");
	
	## Errors Setup ##
	Reg::set("Error.generalErrorMessage", "An error occured. Please contact the administrator.");
    Reg::set("Error.viewErrors", true);
    Reg::set("Error.logErrors",  true);
	//Reg::set("Error.logDirectory", "log"); // Uncomment to specify location of error log generated by framework
	Reg::set("Error.404", "/error404");
	//Reg::set("Error.404", "https://www.google.com");
	
	Reg::set("System.displayPageLoadInfo", true);
    
	## Database Setup ##
	Reg::set("Database.host", "dev.axis41.com");
	Reg::set("Database.username", "wylie");
	Reg::set("Database.password", "SW7dr*kE");
	Reg::set("Database.database", "eric");
	Reg::set("Database.driver", "MySQL");
    Reg::set("Database.viewQueries", false);
	Reg::set('Database.storeQueries', true);
	
	// cache
	Reg::set(array(
		'Cache.enabled'	=> true,
		'Cache.path'		=> Reg::get('Path.physical') . '/cache',
		'Cache.expires'	=> 3600, // 1 hour
	));
	
	## Routes ##
	Config::registerRoute("/pickles/*", array(
		"branch" => "developer",
		"view" => "pickles"
	));
	
	Config::registerRoute("/oranges/*", array(
		"branch" => "developer",
		"view" => "oranges"
	));
	
	Config::registerRoute("/oranges2/:action/*", array(
		"branch" => "developer",
		"view" => "oranges",
		"action" => "list",
		"id" => "hello"
	), array(
		"action" => "(edit|delete|create)"
	));
	
	Autoloader::registerPrefixes(array(
		//'Zend_'	=>	Reg::get('Path.physical').'/vendors/zend/Library'
	));
	
	Autoloader::registerFiles(array(
		//'Doctorine' => Reg::get('Path.physical').'/vendors/doctorine-sandbox/index.php'
	));
	
	Autoloader::registerDirectories(array(
		'Test' => Reg::get('Path.physical').'/vendors/test'
	));
	
	set_include_path(Reg::get('Path.physical').'/vendors/zend/library'.PATH_SEPARATOR.get_include_path());
?>